[build-system]
requires = [
    "setuptools >= 46.4.0",
    "versioningit",
    "wheel ~= 0.32",
]
build-backend = "setuptools.build_meta"

[tool.versioningit.vcs]
method = "hg"
default-tag = "v0.0.0"
