[build-system]
requires = ["setuptools >= 46.4.0", "versioningit"]
build-backend = "setuptools.build_meta"

[tool.versioningit.tag2version]
method = { module = "mypackage", value = "my_tag2version", module-dir = "src" }
