[build-system]
requires = ["setuptools >= 46.4.0", "versioningit"]
build-backend = "setuptools.build_meta"

[tool.versioningit]
default-version = "0.0.0+error"

[tool.versioningit.vcs]
match = ["v*"]
